add_newline = false
[directory]
style = "bold {syn_key}"
format = "[$path]($style)[$read_only]($read_only_style) "
[character]
success_symbol = "[â¯](bold {sem_green})"
error_symbol = "[â¯](bold {sem_red})"
vimcmd_symbol = "[â®]({sem_blue})"
[nix_shell]
format = "[$symbol]($style) "
symbol = "ğŸš"
style = "{ui_prim}"
[git_branch]
symbol = "ï˜ "
format = "[î‚¶]({ui_sec})on [$symbol$branch]($style)[î‚´]({ui_sec}) "
style = "fg:{syn_fun} bg:{ui_sec}"
[git_status]
style = "{sem_yellow}"
stashed = "â‰¡"
[git_state]
style = "{fg_dim}"
format = "([$state( $progress_current/$progress_total)]($style)) "
